language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0
before_install:
  - gem install bundler
install: bundle update --jobs=3 --retry=3

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      name: "Linter"
      language: ruby
      rvm: 2.7.2
      before_install:
        - gem install bundler
      install: bundle update --jobs=3 --retry=3
      script: bundle exec rubocop
